In [1]:
import torch

x = torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


In [2]:
import torch
y = torch.tensor([[1, 2, 3],
[4,5,6]])
print(y)


tensor([[1, 2, 3],
        [4, 5, 6]])


In [15]:
a =torch.zeros(3,2)

In [17]:
o = torch.ones(2,2)
print(o)#all student attend in the class


tensor([[1., 1.],
        [1., 1.]])


In [18]:
r = torch.rand(5, 3)
print(r)

tensor([[0.3575, 0.8300, 0.5927],
        [0.1935, 0.0518, 0.7665],
        [0.9302, 0.3853, 0.0261],
        [0.2640, 0.4922, 0.5393],
        [0.5791, 0.8432, 0.5176]])


In [3]:
a = torch.tensor([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(a)
print(a.shape)



tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])


In [22]:
i = torch.tensor([1,2,3])
print(i[0])
print(i.shape)

d_2 = torch.tensor(
    [
        [1,2,3],[4,5,6]
    ]
)

print(d_2[0,1])



tensor(1)
torch.Size([3])
tensor(2)


In [24]:
a = torch.tensor([1,2,3])
b= torch.tensor([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [4]:
import numpy as np
arr = np.array([1,2,3])
n = torch.from_numpy(arr) #numpy to tensor
print(n)

tensor([1, 2, 3])
